/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menuTiket;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author Fatma
 */
public class yowisBen extends javax.swing.JFrame {
    String kursi;

    /**
     * Creates new form yowisBen
     */
    public yowisBen() {
        initComponents();
        ImageIcon myimage2=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("yowisben.jpg")));
        Image img5 = myimage2.getImage();
        Image img6 = img5.getScaledInstance(yws.getWidth(), yws.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon yowisben=new ImageIcon(img6);
        yws.setIcon(yowisben);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yws = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        C_day = new javax.swing.JComboBox<>();
        t_harga = new javax.swing.JTextField();
        C_waktu = new javax.swing.JComboBox<>();
        t_waktu = new javax.swing.JTextField();
        C_Bayar = new javax.swing.JComboBox<>();
        T_Bayar = new javax.swing.JTextField();
        T_kursi = new javax.swing.JTextField();
        R_1C = new javax.swing.JRadioButton();
        R_1B = new javax.swing.JRadioButton();
        R_1A = new javax.swing.JRadioButton();
        R_1D = new javax.swing.JRadioButton();
        R_1E = new javax.swing.JRadioButton();
        R_1F = new javax.swing.JRadioButton();
        R_2C = new javax.swing.JRadioButton();
        R_2B = new javax.swing.JRadioButton();
        R_2A = new javax.swing.JRadioButton();
        R_2D = new javax.swing.JRadioButton();
        R_2E = new javax.swing.JRadioButton();
        R_2F = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(yws, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 160, 240));

        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        C_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Minggu ", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu" }));
        C_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_dayActionPerformed(evt);
            }
        });
        getContentPane().add(C_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 230, 30));

        t_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_hargaActionPerformed(evt);
            }
        });
        getContentPane().add(t_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 270, 30));

        C_waktu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Waktu--", "13:00", "16:00", "19:00" }));
        C_waktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_waktuActionPerformed(evt);
            }
        });
        getContentPane().add(C_waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 230, 30));

        t_waktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_waktuActionPerformed(evt);
            }
        });
        getContentPane().add(t_waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 270, 30));

        C_Bayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Tunai", "E-Money", " " }));
        C_Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_BayarActionPerformed(evt);
            }
        });
        getContentPane().add(C_Bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 230, 30));

        T_Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_BayarActionPerformed(evt);
            }
        });
        getContentPane().add(T_Bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 270, 30));

        T_kursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_kursiActionPerformed(evt);
            }
        });
        getContentPane().add(T_kursi, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 346, 210, 30));

        R_1C.setText("1C");
        R_1C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_1CActionPerformed(evt);
            }
        });
        getContentPane().add(R_1C, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        R_1B.setText("1B");
        R_1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_1BActionPerformed(evt);
            }
        });
        getContentPane().add(R_1B, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, -1, -1));

        R_1A.setText("1A");
        R_1A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_1AActionPerformed(evt);
            }
        });
        getContentPane().add(R_1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, -1, -1));

        R_1D.setText("1D");
        R_1D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_1DActionPerformed(evt);
            }
        });
        getContentPane().add(R_1D, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, -1, -1));

        R_1E.setText("1E");
        R_1E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_1EActionPerformed(evt);
            }
        });
        getContentPane().add(R_1E, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, -1, -1));

        R_1F.setText("1F");
        R_1F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_1FActionPerformed(evt);
            }
        });
        getContentPane().add(R_1F, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, -1, -1));

        R_2C.setText("2C");
        R_2C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_2CActionPerformed(evt);
            }
        });
        getContentPane().add(R_2C, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, -1, -1));

        R_2B.setText("2B");
        R_2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_2BActionPerformed(evt);
            }
        });
        getContentPane().add(R_2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, -1, -1));

        R_2A.setText("2A");
        R_2A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_2AActionPerformed(evt);
            }
        });
        getContentPane().add(R_2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, -1, -1));

        R_2D.setText("2D");
        R_2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_2DActionPerformed(evt);
            }
        });
        getContentPane().add(R_2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, -1, -1));

        R_2E.setText("2E");
        R_2E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_2EActionPerformed(evt);
            }
        });
        getContentPane().add(R_2E, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, -1, -1));

        R_2F.setText("2F");
        R_2F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_2FActionPerformed(evt);
            }
        });
        getContentPane().add(R_2F, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, -1, -1));

        jButton3.setText("Submit");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menuTiket/bg2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Menu menu = new Menu();
        this.dispose();
        this.setVisible(false);
        menu.pack();
        menu.setLocationRelativeTo(null);
        new Menu().setVisible(true);
        menu.setDefaultCloseOperation(yowisBen.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void C_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_dayActionPerformed
        // TODO add your handling code here:
        int harga;
        if(C_day.getSelectedItem() == "Minggu"){
            harga = 50000;
        }
        else if (C_day.getSelectedItem() == "Senin"){
            harga = 35000;
        }
        else if (C_day.getSelectedItem() == "Selasa"){
            harga = 35000;
        }
        else if (C_day.getSelectedItem() == "Rabu"){
            harga = 35000;
        }
        else if (C_day.getSelectedItem() == "Kamis"){
            harga = 35000;
        }
        else if (C_day.getSelectedItem() == "Jumat"){
            harga = 35000;
        }
        else {
            harga = 50000;
        }

        t_harga.setText(String.valueOf(harga));
    }//GEN-LAST:event_C_dayActionPerformed

    private void t_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_hargaActionPerformed

    private void C_waktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_waktuActionPerformed
        // TODO add your handling code here:
        String waktu;
        if(C_waktu.getSelectedItem() == "13:00"){
            waktu = "13:00";
        }
        else if(C_waktu.getSelectedItem() == "16:00"){
            waktu = "16:00";
        }
        else{
            waktu = "19:00";
        }
        t_waktu.setText(String.valueOf(waktu));
    }//GEN-LAST:event_C_waktuActionPerformed

    private void t_waktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_waktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_waktuActionPerformed

    private void C_BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_BayarActionPerformed
        // TODO add your handling code here:
        String metBayar;
        if(C_Bayar.getSelectedItem() == "Tunai"){
            metBayar = "Tunai";
        }
        else if(C_Bayar.getSelectedItem() == "E-Money"){
            metBayar = "E-Money";
        }
        else{
            metBayar = "Pilih Metode Pembayaran";
        }
        T_Bayar.setText(String.valueOf(metBayar));
    }//GEN-LAST:event_C_BayarActionPerformed

    private void T_BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_BayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_BayarActionPerformed

    private void T_kursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_kursiActionPerformed

    }//GEN-LAST:event_T_kursiActionPerformed

    private void R_1CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_1CActionPerformed
        // TODO add your handling code here:
        if(R_1C.isSelected()){
            kursi = "1C";
        }
        else {
            kursi = "Pilih Kursi";
        }

        T_kursi.setText(String.valueOf(kursi));
    }//GEN-LAST:event_R_1CActionPerformed

    private void R_1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_1BActionPerformed
        // TODO add your handling code here:
        if(R_1B.isSelected()){
            kursi = "1B";
            T_kursi.setText(String.valueOf(kursi));
        }
    }//GEN-LAST:event_R_1BActionPerformed

    private void R_1AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_1AActionPerformed
        // TODO add your handling code here:
        if(R_1A.isSelected()){
            kursi = "1A";
            T_kursi.setText(String.valueOf(kursi));
        }
    }//GEN-LAST:event_R_1AActionPerformed

    private void R_1DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_1DActionPerformed
        // TODO add your handling code here:
        if(R_1D.isSelected()){
            kursi = "1D";
        }
        else {
            kursi = "Pilih Kursi";
        }
        T_kursi.setText(String.valueOf(kursi));
    }//GEN-LAST:event_R_1DActionPerformed

    private void R_1EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_1EActionPerformed
        // TODO add your handling code here:
        if(R_1E.isSelected()){
            kursi = "1E";
        }
        else{
            kursi = "Pilih Kursi";
        }
        T_kursi.setText(String.valueOf(kursi));
    }//GEN-LAST:event_R_1EActionPerformed

    private void R_1FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_1FActionPerformed
        // TODO add your handling code here:
        if(R_1F.isSelected()){
            kursi = "1F";
        }
        else{
            kursi = "Pilih Kursi";
        }
        T_kursi.setText(String.valueOf(kursi));
    }//GEN-LAST:event_R_1FActionPerformed

    private void R_2CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_2CActionPerformed
        // TODO add your handling code here:
        if(R_2C.isSelected()){
            kursi = "2C";
        }
        else{
            kursi = "Pilih Kursi";
        }
        T_kursi.setText(String.valueOf(kursi));
    }//GEN-LAST:event_R_2CActionPerformed

    private void R_2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_2BActionPerformed
        // TODO add your handling code here:
        if(R_2B.isSelected()){
            kursi = "2B";
        }
        else{
            kursi = "Pilih Kursi";
        }
        T_kursi.setText(String.valueOf(kursi));
    }//GEN-LAST:event_R_2BActionPerformed

    private void R_2AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_2AActionPerformed
        // TODO add your handling code here:
        if(R_2A.isSelected()){
            kursi = "2A";
        }
        else{
            kursi = "Pilih Kursi";
        }
        T_kursi.setText(String.valueOf(kursi));
    }//GEN-LAST:event_R_2AActionPerformed

    private void R_2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_2DActionPerformed
        // TODO add your handling code here:
        if(R_2D.isSelected()){
            kursi = "2D";
        }
        else {
            kursi = "Pilih Kursi";
        }
        T_kursi.setText(String.valueOf(kursi));
    }//GEN-LAST:event_R_2DActionPerformed

    private void R_2EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_2EActionPerformed
        // TODO add your handling code here:
        if(R_2E.isSelected()){
            kursi = "2E";
        }
        else{
            kursi = "Pilih Kursi";
        }
        T_kursi.setText(String.valueOf(kursi));
    }//GEN-LAST:event_R_2EActionPerformed

    private void R_2FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_2FActionPerformed
        // TODO add your handling code here:
        if(R_2F.isSelected()){
            kursi = "2F";
        }
        else{
            kursi = "Pilih Kursi";
        }
        T_kursi.setText(String.valueOf(kursi));
    }//GEN-LAST:event_R_2FActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Home h = new Home();
        this.dispose();
        this.setVisible(false);
        h.pack();
        h.setLocationRelativeTo(null);
        new Home().setVisible(true);
        h.setDefaultCloseOperation(yowisBen.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yowisBen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yowisBen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yowisBen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yowisBen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yowisBen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> C_Bayar;
    private javax.swing.JComboBox<String> C_day;
    private javax.swing.JComboBox<String> C_waktu;
    private javax.swing.JRadioButton R_1A;
    private javax.swing.JRadioButton R_1B;
    private javax.swing.JRadioButton R_1C;
    private javax.swing.JRadioButton R_1D;
    private javax.swing.JRadioButton R_1E;
    private javax.swing.JRadioButton R_1F;
    private javax.swing.JRadioButton R_2A;
    private javax.swing.JRadioButton R_2B;
    private javax.swing.JRadioButton R_2C;
    private javax.swing.JRadioButton R_2D;
    private javax.swing.JRadioButton R_2E;
    private javax.swing.JRadioButton R_2F;
    private javax.swing.JTextField T_Bayar;
    private javax.swing.JTextField T_kursi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField t_harga;
    private javax.swing.JTextField t_waktu;
    private javax.swing.JLabel yws;
    // End of variables declaration//GEN-END:variables
}
